### ISSUE TITLE
Peek error: Module not found ....main.bundle.js

### ISSUE THREAD

**Issue by GianniBYoung** [toppair/peek.nvim#11]
**Describe the bug**
After installing the plugin through packer and installing deno I get the error: 

`Peek error: error: Module not found "/home/mine/.local/share/nvim/site/pack/packer/start/peek.nvim/public/main.bundle.js" `

**To Reproduce**
Attempt to run `:PeekOpen` on a fresh install

**Expected behavior**
A window to open with the markdown preview

**Desktop:**
 - OS: [windows wsl ubuntu]
 - `nvim --version`: 
```
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
 - `deno --version`: 
```
deno 1.28.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.1
typescript 4.8.3
```
 - plugin setup:
```lua packer
use({ 'toppair/peek.nvim', run = 'deno task --quiet build:fast' })
-- default config:
require('peek').setup({
  auto_load = true,         -- whether to automatically load preview when
                            -- entering another markdown buffer
  close_on_bdelete = true,  -- close preview window on buffer delete

  syntax = true,            -- enable syntax highlighting, affects performance

  theme = 'dark',           -- 'dark' or 'light'

  update_on_change = true,

  -- relevant if update_on_change is true
  throttle_at = 200000,     -- start throttling when file exceeds this
                            -- amount of bytes in size
  throttle_time = 'auto',   -- minimum amount of time in milliseconds
                            -- that has to pass before starting new render
})
vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})
```

**Comment by edr3x** [comment]
Try installing `libwebkit2gtk` form your package manager, installing that and rebooting should help. I had same issue, doing this resolved mine.

**Comment by GianniBYoung** [comment]
> Try installing `libwebkit2gtk` form your package manager, installing that and rebooting should help. I had same issue, doing this resolved mine, hope this also works on wsl.

libwebkit2gtk-4.0-37 is already installed and up to date ☹

**Comment by toppair** [comment]
> After installing the plugin through packer and installing deno I get the error

The order should be install deno first and then install the plugin. Deno is also required to build the app. Could you remove the plugin and install it again? Looks like build files are missing.

If that doesn't work, provide the output of
`cd /home/mine/.local/share/nvim/site/pack/packer/start/peek.nvim && deno task build:debug`

**Comment by GianniBYoung** [comment]
> > After installing the plugin through packer and installing deno I get the error
> 
> The order should be install deno first and then install the plugin. Deno is also required to build the app. Could you remove the plugin and install it again? Looks like build files are missing.
> 
> If that doesn't work, provide the output of `cd /home/mine/.local/share/nvim/site/pack/packer/start/peek.nvim && deno task build:debug`

I will give it a try when I am back in office monday, thanks for the response!

**Comment by toppair** [comment]
> Do you have any insight for this error?

I can only point you to [this askubuntu question](https://askubuntu.com/questions/993225/whats-the-easiest-way-to-run-gui-apps-on-windows-subsystem-for-linux).
Looks like you may have to install additional software and maybe do some configuring to make it work on wsl.

Also: https://github.com/webview/webview#platform-support

**Comment by GianniBYoung** [comment]
Leaving this comment for posterity's sake, the issue is with wsl. In order for wsl to run gtk apps with out installing a third party x server, wsl must be up to date and the windows build has to be 21364 or higher.

https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by kelbyfaessler** [comment]
@GianniBYoung did you get it working with wsl or did you give up?

**Comment by GianniBYoung** [comment]
> @GianniBYoung did you get it working with wsl or did you give up?

I got it working on my personal wsl instance but not on my work machine. 

The blocker was that my work windows version didn't support gtk apps through wsl so I would have had to run a 3rd party x server which I wasn't interested in trying.

**Comment by erickvneri** [comment]
Hello, everyone

I believe this will be interesting for all the Linux (ubuntu in my case) users around, so...

I had the same issue as all of you and found that the snap-installed deno runtime wasn't enough, because it was installing the deno v1.27.1... which somehow didn't have the necessary permissions to perform the reading.

So, I decided to look at the official installation guides from the [deno site](https://deno.land/manual@v1.32.1/getting_started/installation), and Boom!!

After installing deno from this command, I got deno v1.31.1:

```
curl -fsSL https://deno.land/x/install/install.sh | sh
```
Then, finally I was able to run the command shared by @toppair without any error... this command:

```
cd ~/.local/share/nvim/site/pack/packer/start/peek.nvim && deno task build:debug
```

And `lua require "peek".open` was able to preview my md files =]

Cheers!
