### ISSUE TITLE
The peek plugin window show nothing for previewing..

### ISSUE THREAD

**Issue by JuanZoran** [toppair/peek.nvim#12]
**Describe the bug**
I just follow the guidelines to install this plugin,
and I go the deno-official-website to download deno for that
I use packer to install this plugin, and I get 'installed successfully'
then I open the .md file for preview, and nothing happens

**To Reproduce**
just add this in packer.funcion
```lua
	use({
		"toppair/peek.nvim",
		run = "deno task --quiet build:fast",
		config = function()
            require('peek').setup()
		end,
	})
```
then I open a file named 'a.md', nothing happend
I use `:lua require('peek').open()`, then get a window, just a black for that

**Expected behavior**
just preview md file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 22,04
 - `nvim --version`: 0.8.0
```
```
 - `deno --version`: latest
```
```
 - plugin setup: as i Described
```lua
```
**Additional context**
none

**Comment by JuanZoran** [comment]
sorry about that I dont't know why I can upload the bug.png file.....
I get this 
> Something went really wrong, and we can't process  that file....

**Comment by JuanZoran** [comment]
[bug.zip](https://github.com/toppair/peek.nvim/files/10105371/bug.zip)

**Comment by brancobruyneel** [comment]
> I'm running into the same issue on:
> 
>     * macOS 13.0.1
> 
>     * nvim 0.8.1 (homebrew)
> 
>     * deno 1.28.2
> 
> 
> The `peek.log` contents:
> 
> ```
> INFO      72942    28/11/2022, 11:26:36.206  DENO_ENV: undefined --logfile=/Users/steve.loveless/.local/state/nvim/peek.log --theme=dark --syntax
> INFO      72942    28/11/2022, 11:26:36.217  listening on 0.0.0.0:57658 
> INFO      72942    28/11/2022, 11:27:23.459  SIGNAL:  SIGTERM
> ```
> 
> FWIW, I was curious so I tried doing this in `app/src/main.ts`, but this doesn't seem to change the behavior:
> 
> ```ts
> // const DENO_ENV = Deno.env.get('DENO_ENV');
> const DENO_ENV = 'development';
> ```

Same here with similar setup

**Comment by toppair** [comment]
@JuanZoran @turboladen @brancobruyneel

Can you guys check whether it is fixed now, after #23?

**Comment by JuanZoran** [comment]
I just install deno and then add this to my config file
>  plugins:add {
    'toppair/peek.nvim',
    build = 'deno task --quiet build:fast',
}

but it builds failed, here is debug message:
`error: Error reading config file file:///home/zoran/.local/share/nvim/lazy/peek.nvim/deno.json: Permission denied (os error 13)`

I am freshman about deno, I don't how can I solve this problem

**Comment by roccoblues** [comment]
I've switched to native browser mode before to workaround the issue. Just switched back and can confirm that it works now. Thanks @toppair @jakehl!

**Comment by brancobruyneel** [comment]
Can also confirm it works, thanks!
