### ISSUE TITLE
Save the rendered html to a file

### ISSUE THREAD

**Issue by jeffbuttars** [toppair/peek.nvim#13]
I love the output created by peek.nvim, but I only get a preview.

I would love it if I could save the preview as an html file. Either by a right click on the preview window and/or by a command
such as `PeekSave [filename]`

Where by default the saved filename would be the original markdown filename, but with a `.html` suffix instead of `.md`.
But an option to supply a filename to save as.

**Comment by jakehl** [comment]
I won't speak for the maintainer but this feels out of scope for the project. However, it is a nice part of the workflow, what I have done in the past is just save the webpage from my browser, which can be done when you use the browser mode rather than the built in webview.

**Comment by jeffbuttars** [comment]
Thanks for the tip.
The 'browser' mode feature is great. Makes it easy to save as PDF very easy as well.

This satisfies the feature(s) I was looking for, I'll close this.
