### ISSUE TITLE
Failed to preview markdown on windows

### ISSUE THREAD

**Issue by yehuohan** [toppair/peek.nvim#14]
**Describe the bug**
Failed to preview markdown on windows

**To Reproduce**

When run `lua require('peek').open()`, error was caught: 

```
Peek error: error: Uncaught Error: 目录名称无效。 (os error 267)
const webview = Deno.run({
                     ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at file:///C:/apps/dotvim/bundle/peek.nvim/public/main.bundle.js:84239:22
```
(`目录名称无效` means `invalid directory name`)

**Expected behavior**
Markdown previewer startup successful.

**Desktop (please complete the following information):**
 - OS: windows
 - `nvim --version`:
```
NVIM v0.9.0-dev-465+ga505c1acc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az478-812
```
 - `deno --version`:
```
deno 1.29.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```
 - plugin setup:
```lua
    local peek = require('peek')
    peek.setup{
        auto_load = false,
        syntax = true,
        theme = 'light',
    }
```

**Additional context**
(Firstly I saw some specified lua code for windows path, so I think peek.nvim supports windows. If not, please let me know and I will close this issue)
I had a simpe debug about this issue. It's seems the expression [dirname(new URL(Deno.mainModule).pathname](https://github.com/toppair/peek.nvim/blob/master/app/src/main.ts#L84) is not supported on Windows.
I tried some fix as the picture show below:

![a](https://user-images.githubusercontent.com/17680752/207826498-164f9d65-c8d3-4582-b5ee-07c115c51600.png)

After `deno task build` and `lua require('peek').open()`, the peek previewer is startup. But unfortunately, there's nothing displayed on the previewer window like below:

![b](https://user-images.githubusercontent.com/17680752/207827378-2ebca067-9e23-4fbd-bb7c-62b9ce9cee57.png)

And the output of `deno task build`  is attached below:

```
Task build deno run --allow-run --allow-net --allow-read --allow-write --allow-env --no-check scripts/build.js
Bundle file:///C:/apps/dotvim/bundle/peek.nvim/app/src/webview.ts
Bundle file:///C:/apps/dotvim/bundle/peek.nvim/app/src/main.ts
Emit "public/webview.js" (284.72KB)
Emit "public/main.bundle.js" (2.48MB)
Bundle file:///C:/apps/dotvim/bundle/peek.nvim/client/src/script.ts
Emit "public/script.bundle.js" (14.13KB)
```

**Comment by hulufei** [comment]
@yehuohan I don't have windows by hand. But could you try #16 to see if it works?

**Comment by yehuohan** [comment]
> @yehuohan I don't have windows at hand. But could you try #16 to see if it works?

Sorry for late test.
I tested with

```vim
Plug 'hulufei/peek.nvim', { 'branch': 'use-browser', 'do': 'deno task --quiet build:fast' }
```

But unfortunately, markdown was failed to preview.
It does open the url `http://0.0.0.0:1557/?theme=light` in browser, but `Failed to connected` like the picture below.

![failed](https://user-images.githubusercontent.com/17680752/215514080-0546a79b-4017-4c18-9e7f-7b411e81087d.png)

**Comment by toppair** [comment]
> Firstly I saw some specified lua code for windows path, so I think peek.nvim supports windows

> It's seems the expression dirname(new URL(Deno.mainModule).pathname is not supported on Windows.

@yehuohan I wrote some windows specific code where I thought it might make a difference. Unfortunately, I don't own any windows machine so I'm unable to test things out. If someone with an access to a windows machine would be willing to come up with a comprehensive solution here, that would be great.

Meanwhile, can you check if [this PR](https://github.com/toppair/peek.nvim/pull/23) fixed the connectivity part of your problem?

**Comment by yehuohan** [comment]
@toppair, Thank your work and @jakehl's PR, now it works perfectly execpt some extra small fix for windows as detailed below:

In line https://github.com/toppair/peek.nvim/blob/571f14c795e8edd5a21e435f42f37c9bec4a8e16/app/src/main.ts#L179 , windows only support SIGINT and SIGBREAK. So some signals should be disabled for windows.
