### ISSUE TITLE
Error: `gtk_main_quit: assertion 'main_loops != NULL'`

### ISSUE THREAD

**Issue by aspeddro** [toppair/peek.nvim#2]
When closing the window on `i3`: `$mod+q`

```
Peek error:
(deno:70428): Gtk-CRITICAL **: 19:15:12.704: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by toppair** [comment]
It basically means that you've closed the window manually from outside neovim that's all. Should probably be silenced. Will give it a thought.
