### ISSUE TITLE
Accept additional filetypes

### ISSUE THREAD

**Issue by Zethtren** [toppair/peek.nvim#22]
**Is your feature request related to a problem? Please describe.**
I am having an issue when using another extension that overrides the file type of markdown files.

The syntax is the same and I have opened an issue there to see if I can maintain the additional Link highlights / tree-sitter data while still using the markdown file type.

But, if it proves to be too difficult on their end, is there a way you could allow additional file types via the setup function? It seems like it may be an easier feature to implement here.

**Describe the solution you'd like**
require('peek').setup({
    allow_filetypes = {'markdown', 'telekasten', 'etc'}
})

**Comment by HerCerM** [comment]
There is an open PR which seems to implement this feature: https://github.com/toppair/peek.nvim/pull/15
