### ISSUE TITLE
Webview: set default window size and don't autofocus

### ISSUE THREAD

**Issue by letscho123** [toppair/peek.nvim#25]
**Is your feature request related to a problem? Please describe.**
Currently, the `Webview` window opens always in the same size and has the focus by default, but changing it is not easily configurable.

**Describe the solution you'd like**
Add options to the configuration to set the default `Webview` window size and position and if it has focus or not.

**Additional context**
Otherwise great plugin.

**Comment by toppair** [comment]
The easiest and most straightforward way of achieving that is [utilizing your window manager](https://github.com/toppair/peek.nvim#mag-preview-window).
