### ISSUE TITLE
Support offline mode by serving 3rd party styles/javascripts from localhost

### ISSUE THREAD

**Issue by tom-kuca** [toppair/peek.nvim#31]
**Is your feature request related to a problem? Please describe.**
Currently, the preview is not loading for me, I see only loading dots in the webview. There is an error in Console

    Uncaught ReferenceError: mermaid is not defined

The problem is not with the plugin, it's a third party error. URL https://unpkg.com/mermaid@9.2.1/dist/mermaid.min.js returns an error, the host is down.

**Describe the solution you'd like**
I would prefer to download the dependencies during installation, so that the plugin works even if they are not available. I see two of them

* https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
* https://unpkg.com/mermaid@9.2.1/dist/mermaid.min.js

There is already a local reference to `github-markdown.min.css`.

**Comment by razzat008** [comment]
I'm also facing the same issue as you, which is loading dots are seen in the preview

> I would prefer to download the dependencies during installation, 

By dependencies, did you mean the two links you've provided?
If yes could you tell me on which directory I could put them into to get the preview to work.

Thanks.

**Comment by tom-kuca** [comment]
> By dependencies, did you mean the two links you've provided?

Yes.

> If yes could you tell me on which directory I could put them into to get the preview to work.

As a workaround, you can edit `~/.local/share/nvim/lazy/peek.nvim/public/index.html` and change the URL. I would put them to the same directory, together with e.g. `github-markdown.min.css`.
