### ISSUE TITLE
Webview window makes error bell sound when using keybinds on MacOS 13.3.1

### ISSUE THREAD

**Issue by loqusion** [toppair/peek.nvim#37]
### Versions

`NVIM 0.10.0-dev-120+gdd8781128-Homebrew`
`deno 1.32.5`
`macOS 13.3.1`

**Comment by snoblenet** [comment]
seem here

**Comment by toppair** [comment]
Possibly fixed by 3f7366f.

**Comment by loqusion** [comment]
Seems to have done the trick, thanks!
