### ISSUE TITLE
Blue dot in the Markdown preview

### ISSUE THREAD

**Issue by HerCerM** [toppair/peek.nvim#41]
**Describe the bug**
There is a blue dot to the left of the Markdown preview.

**To Reproduce**
Open the peek.nvim preview for any Markdown document.

**Expected behavior**
The Markdown preview is rendered without a blue dot.

**Screenshots**
This is the blue dot I do not expect to see in the preview (indicated by the red arrow).
![peek_bluedot](https://github.com/toppair/peek.nvim/assets/42811720/83437d3d-857a-426b-ab21-457420c40802)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur v11.6
 - `nvim --version`:
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```
 - `deno --version`:
```
deno 1.30.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```
 - plugin setup:
```lua
peek.setup {}
```
**Additional context**
The blue dot is also present in:
- the light mode: `peek.setup { theme = "light" }`, and
- in the browser: `peek.setup { app = "browser" }`

**Comment by toppair** [comment]
Purpose of the dot is to roughly mark the position of cursor in document. Haven't heard strong enough argument against it yet, so we'll leave it there.

**Comment by HakonHarnes** [comment]
@toppair Can you consider adding an option for disabling it?
