### ISSUE TITLE
Peek error: error: Module not found `.../public/main.bundle.js`

### ISSUE THREAD

**Issue by dasupradyumna** [toppair/peek.nvim#47]
**Describe the bug**
I have followed the instructions provided in the repository to install the plugin.
- Installed `deno` binary from the website first
- Installed the plugin using `lazy.nvim` package manager
- The `build` part of the command `deno task --quiet build:fast` fails with an error:
```txt
error: Node specifiers have not yet been implemented for this subcommand (https://github.com/denoland/deno/issues/15960). Found: node:punycode
```

**Steps To Reproduce**
1. Open NeoVim instance and a `markdown` file
2. Execute `:lua require('peek').open()` command, which throws an error:
```txt
Peek error: error: Module not found "file:///home/kenja/.local/share/nvim/lazy/peek.nvim/public/main.bundle.js".
```

**Expected behavior**
A markdown preview should open when `:lua require('peek').open()` is executed

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - `nvim --version`:
```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
 - `deno --version`:
```
deno 1.34.2 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4
```
 - plugin setup:
```lua
require('peek').setup()
```
**Additional context**
Similar issues were noted in #11, #28 and #46
Workarounds (manual installation) provided in these issues failed with the same error above `error: Node specifiers ...`

**Comment by sdrap** [comment]
Exactly the same environment and same problem. Did the same workarounds and got the same errors

**Comment by cloudsftp** [comment]
I have the exact same issue, but I installed it using Packer.

After playing around with different deno versions, I got a better error message (with deno v1.25.0):
```
error: Remote modules are not allowed to import local modules. Consider using a dynamic import instead.
  Importing: node:punycode
    at https://esm.sh/v125/markdown-it@13.0.1/denonext/markdown-it.mjs:2:328
```

Only `main.ts` doesn't compile, the other targets are fine.

This is my first time working with deno so I don't really know how to fix this.
Maybe the installer script should use a different command to bundle `src/main.ts` since `deno bundle` is deprecated?

I tried building `main.ts` with `esbuild app/src/main.ts --bundle --outdir=public`, which then produces `public/main.js`.
So you have to also change the `run` command in `deno.json`.
This script then had a problem requiring some package dynamically.
Maybe this will help someone figure out a solution.

**Comment by cloudsftp** [comment]
I replaced the bundling process with [`deno_emit`](https://github.com/denoland/deno_emit/blob/main/js/README.md). This works nice.

I will replace all other bundlings with this also and open a PR. In the meantime you can try my version here: https://github.com/cloudsftp/peek.nvim/tree/bundle

**Comment by fengzhiken** [comment]
I am trying to use your version, @cloudsftp ,  I still get the same error. Am I doing something wrong?

![image](https://github.com/toppair/peek.nvim/assets/105645418/55404e3e-61d9-4da6-b5b9-899881514345)

**Comment by cloudsftp** [comment]
> I am trying to use your version, @cloudsftp ,  I still get the same error. Am I doing something wrong?

@fengzhiken Unfortunately, my version only works with older versions of deno. Refer to the pull request, I linked.

**Comment by qizidog** [comment]
same problem, env as follow
```bash
[dogqizi@MacDog lua (lazyvim ✗)]❱❱❱ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
[dogqizi@MacDog lua (lazyvim ✗)]❱❱❱ deno --version
deno 1.34.3 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

**Comment by GervinFung** [comment]
facing the same problem when I'm trying out this tool, in the meantime, I think u guys can try [this markdown preview tool](https://github.com/iamcco/markdown-preview.nvim)

**Comment by serginhohigh** [comment]
> facing the same problem when I'm trying out this tool, in the meantime, I think u guys can try [this markdown preview tool](https://github.com/iamcco/markdown-preview.nvim)

This plugin is laggin with puml. Periodically raise strange exceptions when code is ok

**Comment by wuliuqii** [comment]
Same problem in NixOS.

**Comment by pabloqpacin** [comment]
Can confirm the tweaks at #50 fix the issue :+1:

**Comment by john-kenealy** [comment]
I had the same problem and implemented the four lines from the PR @pabloqpacin recommended. Ran a fresh `deno task --quiet build` and peek is now working as expected.

**Comment by inactdev** [comment]
Can also confirm that @pabloqpacin fix works ! Used @john-kenealy's comment above 👍

**Comment by bassamsdata** [comment]
I had this issue as well, but using @saimo PR and then fresh deno build solve the issue.

**Comment by dasupradyumna** [comment]
@toppair Could you please check the mentioned PR and merge it? There have been multiple confirmations already about the PR fixing this issue.
