### ISSUE TITLE
throttle_time should a number not string

### ISSUE THREAD

**Issue by jdhao** [toppair/peek.nvim#5]
When I run the setup, I see the following error:

> packer.nvim: Error running config for peek.nvim: ...ata\site\pack\packer\start\peek.nvim/lua/peek/config.lua:35: throttle_time: expected number, got string

So the default setting `throttle_time = 'auto'` should be updated or the code need to consider this case?

**Comment by toppair** [comment]
> So the default setting throttle_time = 'auto' should be updated or the code need to consider this case?

The latter, it should simply pass the validation.
