### ISSUE TITLE
Question about the instance of deno in use 

### ISSUE THREAD

**Issue by cjnucette** [toppair/peek.nvim#53]
When this plugin is used in NixOS it throws an error stating that deno can't find shared libraries.
I have deno installed globally, so I'm thinking this plugin is using its own instance of deno. If so is there an option to tell it to use the globally installed one?

**Comment by toppair** [comment]
Here's a snippet of how the deno app is spawned, using `vim.fn.jobstart` API:

https://github.com/toppair/peek.nvim/blob/112320b42785aa2445175049f80f46d199ed0244/lua/peek/app.lua#L40C1-L55C1

So the deno in use is whatever version of deno spawned this way in your Neovim instance, which I would assume is globally installed one in most cases. Having your $PATH properly configured to point to the right executable may also be relevant.
