### ISSUE TITLE
Peek error: Use of deprecated "Deno.run()" API

### ISSUE THREAD

**Issue by rizkyilhampra** [toppair/peek.nvim#54]
**Describe the bug**
Showing error in `nvim-notify` after closed the browser. i have try close peek with `PeekClose` and exit the browser when is running, both of them give me notify error. 

**To Reproduce**
1. Open neovim and `markdown` file
2. Run command `PeekOpen`
3. After the browser open and run, close with `PeekClose` or exit the browser

**Expected behavior**
Not showing notify error after closed

**Screenshots**
![2024-01-26-142450_hyprshot](https://github.com/toppair/peek.nvim/assets/71933349/8d02d173-0899-43b8-99c9-b7185b1eb078)

**Desktop (please complete the following information):**
 - OS: Endeavour
 - `nvim --version`:
```
NVIM v0.10.0-dev-2110+g2fce95ec4
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
```
 - `deno --version`:
```
deno 1.40.1 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3
```
 - plugin setup:
```lua
return
{
    "toppair/peek.nvim",
    event = { "VeryLazy" },
    build = "deno task --quiet build:fast",
    config = function()
        require("peek").setup({
            app = {
                'chromium',
                '--new-window'
            }
        })
        -- refer to `configuration to change defaults`
        vim.api.nvim_create_user_command("PeekOpen", require("peek").open, {})
        vim.api.nvim_create_user_command("PeekClose", require("peek").close, {})
    end,
}
```
**Additional context**
Sorry i don't know how to debug and get full log. so i just copied from command `:Notifications` based `nvim-notify`.
```
message = { 'Peek error: warning: Use of deprecated "Deno.run()" API. This API will be removed in Deno 2.', "", "Stack trace:", "  at open (file:///home/aquila/.l
ocal/share/nvim/lazy/peek.nvim/public/main.bundle.js:1537:29)", "  at file:///home/aquila/.local/share/nvim/lazy/peek.nvim/public/main.bundle.js:107268:5", "  at file
:///home/aquila/.local/share/nvim/lazy/peek.nvim/public/main.bundle.js:107276:3", "", 'hint: Use "Deno.Command()" API instead.', "", 'warning: Use of deprecated "Deno
.serveHttp()" API. This API will be removed in Deno 2.', "", "Stack trace:", "  at file:///home/aquila/.local/share/nvim/lazy/peek.nvim/public/main.bundle.js:107237:3
5", "", "hint: Use `Deno.serve()` instead.", "", "" },
```

**Comment by LuposX** [comment]
@rizkyilhampra did you figure something out to surpress that warning?
