### ISSUE TITLE
Invalid certificate during install

### ISSUE THREAD

**Issue by ckt114** [toppair/peek.nvim#62]
**Describe the bug**
I'm getting the error below when during install.
```
        ^[[0m^[[32mDownload^[[0m https://deno.land/x/emit@0.38.1/mod.ts
                             ^[[0m^[[1m^[[31merror^[[0m: Import 'https://deno.land/x/emit@0.38.1/mod.ts' failed: error sending request for url (https://deno.land/x/emit@0.38.1/mod.ts): error
                             trying to connect: invalid peer certificate: UnknownIssuer
                                 at ^[[0m^[[36mfile:///Users/ctran/.local/share/nvim-nvchad/lazy/peek.nvim/scripts/build.js^[[0m:^[[0m^[[33m1^[[0m:^[[0m^[[33m24^[[0m
```

I think it's b/c my company blocks that DNS. Is there a way to install it without building it from scratch?

**To Reproduce**
Install peek.nvim per installation steps.

**Expected behavior**
Should install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Sonoma 14.4.1

 - `nvim --version`:
```
v0.9.5
```
 - `deno --version`:
```
1.43.1
```
 - plugin setup:
```lua
{
    "toppair/peek.nvim",
    event = { "VeryLazy" },
    build = "deno task --quiet build:fast",
    config = function()
        require("peek").setup()
        vim.api.nvim_create_user_command("PeekOpen", require("peek").open, {})
        vim.api.nvim_create_user_command("PeekClose", require("peek").close, {})
    end,
}
```
**Additional context**

**Comment by ckt114** [comment]
So I have another mac that has the same Sonoma version and I was able to have it working on the other mac and I copied the `~/.local/share/nvim-nvchad/lazy/peek.nvim` folder from the other mac over. However, when I toggle to open with `:lua require("peek").open()` the OS popped-up an option to allow to execute and I chose yes but then nothing happens.

Are there any logs that I can check to see what happens? Why it's not doing anything?

Thanks.

**Comment by kraxli** [comment]
> **Describe the bug** I'm getting the error below when during install.
> 
> ```
>         ^[[0m^[[32mDownload^[[0m https://deno.land/x/emit@0.38.1/mod.ts
>                              ^[[0m^[[1m^[[31merror^[[0m: Import 'https://deno.land/x/emit@0.38.1/mod.ts' failed: error sending request for url (https://deno.land/x/emit@0.38.1/mod.ts): error
>                              trying to connect: invalid peer certificate: UnknownIssuer
>                                  at ^[[0m^[[36mfile:///Users/ctran/.local/share/nvim-nvchad/lazy/peek.nvim/scripts/build.js^[[0m:^[[0m^[[33m1^[[0m:^[[0m^[[33m24^[[0m
> ```
> 
> I think it's b/c my company blocks that DNS. Is there a way to install it without building it from scratch?
> 
> **To Reproduce** Install peek.nvim per installation steps.
> 
> **Expected behavior** Should install.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS] Mac Sonoma 14.4.1
> 
>     * `nvim --version`:
> 
> 
> ```
> v0.9.5
> ```
> 
>     * `deno --version`:
> 
> 
> ```
> 1.43.1
> ```
> 
>     * plugin setup:
> 
> 
> ```lua
> {
>     "toppair/peek.nvim",
>     event = { "VeryLazy" },
>     build = "deno task --quiet build:fast",
>     config = function()
>         require("peek").setup()
>         vim.api.nvim_create_user_command("PeekOpen", require("peek").open, {})
>         vim.api.nvim_create_user_command("PeekClose", require("peek").close, {})
>     end,
> }
> ```
> 
> **Additional context** Add any other context about the problem here.

I had the same error on Windows 11 which I have been able to solve by setting the environment variable `DENO_TLS_CA_STORE=system ` (on `linux` you could set `export DENO_TLS_CA_STORE=system ` in your `.bashrc` / `.zshrc` / ...). However, I also do not get a pop up executing the command `PeekOpen`

**Comment by ckt114** [comment]
Thanks @kraxli. Adding that evar works for me and the markdown opens as well.

Here are the steps I took so hopefully it'll work for you too.

1. Set `enabled = false` for the peek.nvim plugin
2. Restart nvim
3. Run `:Lazy` and press `Shift+x` to clean out the old stuff
4. Run `export DENO_TLS_CA_STORE=system`
5. Set `enabled = true` for peek.nvim plugin
6. Run vim again, in the same session as the export above
